const SUPABASE_URL="YOUR_SUPABASE_URL";const SUPABASE_ANON_KEY="YOUR_SUPABASE_ANON_KEY";
let sb=null;if(window.supabase&&SUPABASE_URL.startsWith("http")&&!SUPABASE_ANON_KEY.startsWith("YOUR_"))sb=supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
const $=id=>document.getElementById(id);
const pages=["dashboard","profiles","homepage","requests","payments","reports","content","settings"];
function msg(id,t,ok=true){const e=$(id);if(e){e.textContent=t;e.style.color=ok?"#28733c":"#9b3030";}}
function go(p){pages.forEach(x=>$(x)?.classList.toggle("active-page",x===p));document.querySelectorAll("[data-page]").forEach(b=>b.classList.toggle("active",b.dataset.page===p));$("pageTitle").textContent=p[0].toUpperCase()+p.slice(1);if(p==="profiles")loadProfiles();if(p==="homepage")loadHome();if(p==="content")loadContent();}
document.addEventListener("click",e=>{const b=e.target.closest("[data-page]");if(b)go(b.dataset.page)});
function loginView(){ $("loginView").classList.remove("hidden");$("appView").classList.add("hidden");}
function appView(s){$("loginView").classList.add("hidden");$("appView").classList.remove("hidden");$("adminUser").textContent=s.user.email||"Admin";loadDashboard();}
async function boot(){if(!sb){msg("loginMessage","Add your existing Supabase URL and publishable/anon key in admin.js.",false);return}const {data:{session}}=await sb.auth.getSession();if(session)appView(session);else loginView();sb.auth.onAuthStateChange((_e,s)=>s?appView(s):loginView());}
$("loginForm").onsubmit=async e=>{e.preventDefault();if(!sb)return;const{error}=await sb.auth.signInWithPassword({email:$("adminEmail").value.trim(),password:$("adminPassword").value});if(error)msg("loginMessage",error.message,false)};
$("logoutBtn").onclick=()=>sb?.auth.signOut();$("refreshBtn").onclick=loadDashboard;
async function loadDashboard(){if(!sb)return;const a=await sb.from("profiles").select("id",{count:"exact",head:true});const b=await sb.from("profiles").select("id",{count:"exact",head:true}).eq("is_active",true);const since=new Date(Date.now()-604800000).toISOString();const c=await sb.from("profiles").select("id",{count:"exact",head:true}).gte("created_at",since);$("totalProfiles").textContent=a.count??0;$("activeProfiles").textContent=b.count??0;$("newProfiles").textContent=c.count??0;}
let profileData=[];
async function loadProfiles(){const body=$("profilesBody");body.innerHTML="<tr><td colspan=7>Loading...</td></tr>";const r=await sb.from("profiles").select("id,full_name,gender,date_of_birth,age,city,state,surname,profile_photo,photo_url,is_active,created_at").order("created_at",{ascending:false}).limit(500);if(r.error){body.innerHTML=`<tr><td colspan=7>${esc(r.error.message)}</td></tr>`;return}profileData=r.data||[];renderProfiles(profileData);}
function age(d,a){if(!d)return a||"â€”";const b=new Date(d),n=new Date();let x=n.getFullYear()-b.getFullYear();if(n.getMonth()<b.getMonth()||(n.getMonth()==b.getMonth()&&n.getDate()<b.getDate()))x--;return x}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function renderProfiles(list){$("profilesBody").innerHTML=list.length?list.map(p=>{const im=p.profile_photo||p.photo_url||"";return`<tr><td><div class="profile-cell">${im?`<img class="avatar" src="${esc(im)}">`:`<div class="avatar"></div>`}<div><b>${esc(p.full_name||"Unnamed")}</b><small>${esc(p.surname||"")}</small></div></div></td><td>${esc(p.gender||"â€”")}</td><td>${age(p.date_of_birth,p.age)}</td><td>${esc(p.city||"â€”")}</td><td><span class="status ${p.is_active?"":"off"}">${p.is_active?"Active":"Inactive"}</span></td><td>${p.created_at?new Date(p.created_at).toLocaleDateString():"â€”"}</td><td><button class="action-btn" onclick="toggleProfile('${p.id}',${!!p.is_active})">${p.is_active?"Deactivate":"Activate"}</button></td></tr>`}).join(""):"<tr><td colspan=7>No profiles found.</td></tr>"}
$("profileSearch").oninput=e=>{const q=e.target.value.toLowerCase();renderProfiles(profileData.filter(p=>[p.full_name,p.city,p.state,p.surname,p.gender].filter(Boolean).join(" ").toLowerCase().includes(q)))};
async function toggleProfile(id,on){const r=await sb.from("profiles").update({is_active:!on}).eq("id",id);if(r.error)alert(r.error.message);else loadProfiles();}
async function loadHome(){const r=await sb.from("site_settings").select("*").eq("id","homepage").maybeSingle();if(r.error||!r.data)return;const d=r.data;for(const[k,id]of Object.entries({hero_eyebrow:"homeEyebrow",hero_heading:"homeHeading",hero_description:"homeDescription",primary_button:"homePrimary",secondary_button:"homeSecondary",featured_profile_id:"featuredProfileId",logo_url:"siteLogoUrl",announcement:"homeAnnouncement"}))$(id).value=d[k]||"";}
$("homepageForm").onsubmit=async e=>{e.preventDefault();const d={id:"homepage",hero_eyebrow:$("homeEyebrow").value,hero_heading:$("homeHeading").value,hero_description:$("homeDescription").value,primary_button:$("homePrimary").value,secondary_button:$("homeSecondary").value,featured_profile_id:$("featuredProfileId").value||null,logo_url:$("siteLogoUrl").value,announcement:$("homeAnnouncement").value,updated_at:new Date().toISOString()};const r=await sb.from("site_settings").upsert(d);msg("homeMsg",r.error?.message||"Homepage settings saved.",!r.error);}
async function loadContent(){const r=await sb.from("site_settings").select("*").eq("id","content").maybeSingle();if(r.error||!r.data)return;const d=r.data;for(const[k,id]of Object.entries({about_title:"aboutTitle",about_text:"aboutText",contact_email:"contactEmail",contact_whatsapp:"contactWhatsapp",privacy_text:"privacyText",terms_text:"termsText"}))$(id).value=d[k]||"";}
$("contentForm").onsubmit=async e=>{e.preventDefault();const d={id:"content",about_title:$("aboutTitle").value,about_text:$("aboutText").value,contact_email:$("contactEmail").value,contact_whatsapp:$("contactWhatsapp").value,privacy_text:$("privacyText").value,terms_text:$("termsText").value,updated_at:new Date().toISOString()};const r=await sb.from("site_settings").upsert(d);msg("contentMsg",r.error?.message||"Website content saved.",!r.error);}
boot();
